name: app
description: Client for Leonardo.ai api
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  freezed_annotation: ^2.4.1
  go_router: ^13.0.0
  intl: ^0.18.0
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3
  secure_storage_service:
    path: packages/secure_storage_service

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.7
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true
